title: Archis Gore
description: >-
  Engineer, founder, security researcher. Diversity-as-defense work
  spanning bytecode, calling convention, kernel ABI, and custom ISA.
author:
  name: Archis Gore
  email: me@archisgore.com
url: "https://archisgore.com"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
  - .gitignore
